
static const char http_Form_hml[] = "<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"<title>Document</title>"
"</head>"
"<body>"
"<form method='POST' action='echo' enctype='multipart/form-data'>"
"<input type='file' name='update'> <br />"
"<input type='text' name=\"text1\" value=\"1\"> <br />"
"<input type='text' name=\"text2\" value=\"2\"><br />"
"<input type='text' name=\"text3\" value=\"3\"><br />"
"<input type='submit' value='Update'>"
"</form>"
"</body>"
"</html>";

static const char http_Json_hml[] = "<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"initial-scale=1.0, maximum-scale=1.0, user-scalable=no\" />"
"<title>测试 </title>"
"<link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.yihisxminiid.com/static/wapui/hui.css\" />"
"</head>"
"<body>"
"<div class=\"hui-wrap\">"
"<div style=\"padding:20px 28px;\">"
"<button type=\"button\" class=\"hui-button hui-button-large\" id=\"btn1\" style=\"margin-top:15px;\">获取数据 GET</button>"
"<button type=\"button\" class=\"hui-button hui-button-large\" id=\"btn2\" style=\"margin-top:15px;\">发送数据 POST</button>"
"<button type=\"button\" class=\"hui-button hui-button-large\" id=\"btn5\" style=\"margin-top:15px;\">GET JSON</button>"
"<button type=\"button\" class=\"hui-button hui-button-large\" id=\"btn6\" style=\"margin-top:15px;\">POST 数据形式为JSON</button>"
"</div></div>"
"<script type=\"text/javascript\" src=\"https://sxlogin.oss-cn-shenzhen.aliyuncs.com/wapid/new/hui.js\" charset=\"UTF-8\"></script>"
"<script type=\"text/javascript\">"
"hui('#btn1').click(function () {"
"hui.get("
"'hello',"
"function (res) {"
"console.log(res);"
"hui.toast(res);"
"},"
"function (e) {"
"hui.iconToast('读取消息失败', 'warn');"
"}"
");"
"});"
"hui('#btn2').click(function () {"
"hui.post("
"'echo',"
"{ name: 'hcoder', age: 18 },"
"function (res) {"
"console.log(res);"
"hui.toast(res);"
"},"
"function (e) {"
"hui.iconToast('读取消息失败', 'warn');"
"}"
");"
"});"
"hui('#btn5').click(function () {"
"hui.getJSON("
"'json',"
"function (res) {"
"console.log(res);"
"hui.toast(res.name + ' 版本 : ' + res.verson);"
"},"
"function (e) {"
"hui.iconToast('读取消息失败', 'warn');"
"}"
");"
"});"
"hui('#btn6').click(function () {"
"hui.ajax({"
"url: 'echo',"
"type: 'POST',"
"data: {"
"name: \"hcoder\","
"age: 22,"
"sex: \"男\""
"},"
"beforeSend: function () { hui.loading(); },"
"complete: function () { hui.closeLoading(); },"
"ContentType: \"application/json\","
"success: function (res) {"
"console.log(res);"
"console.log(res.name);"
"},"
"error: function (e) {"
"console.log(JSON.stringify(e));"
"hui.iconToast('读取消息失败', 'warn');"
"},"
"backType: \"JSON\""
"});"
"});"
"</script>"
"</body>"
"</html>";

static const char Html[]="<!DOCTYPE html>"
"<html lang=\"en\"><head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"</head><body>"
"<form method='POST' action='echo' enctype='multipart/form-data'>"
"<input type='text' name=\"text\">"
"<input type='submit' value='Update'>"
"</form></body>"
"</html>";
